package games.thecodewarrior.bitfont.editor.utils.extensions

operator fun MatchResult?.component1(): String = (this ?: throw IllegalArgumentException("Can't destructure null MatchResult")).groupValues.getOrNull(0) ?: ""
operator fun MatchResult?.component2(): String = (this ?: throw IllegalArgumentException("Can't destructure null MatchResult")).groupValues.getOrNull(1) ?: ""
operator fun MatchResult?.component3(): String = (this ?: throw IllegalArgumentException("Can't destructure null MatchResult")).groupValues.getOrNull(2) ?: ""
operator fun MatchResult?.component4(): String = (this ?: throw IllegalArgumentException("Can't destructure null MatchResult")).groupValues.getOrNull(3) ?: ""
operator fun MatchResult?.component5(): String = (this ?: throw IllegalArgumentException("Can't destructure null MatchResult")).groupValues.getOrNull(4) ?: ""
operator fun MatchResult?.component6(): String = (this ?: throw IllegalArgumentException("Can't destructure null MatchResult")).groupValues.getOrNull(5) ?: ""
operator fun MatchResult?.component7(): String = (this ?: throw IllegalArgumentException("Can't destructure null MatchResult")).groupValues.getOrNull(6) ?: ""
operator fun MatchResult?.component8(): String = (this ?: throw IllegalArgumentException("Can't destructure null MatchResult")).groupValues.getOrNull(7) ?: ""
operator fun MatchResult?.component9(): String = (this ?: throw IllegalArgumentException("Can't destructure null MatchResult")).groupValues.getOrNull(8) ?: ""
operator fun MatchResult?.component10(): String = (this ?: throw IllegalArgumentException("Can't destructure null MatchResult")).groupValues.getOrNull(9) ?: ""
operator fun MatchResult?.component11(): String = (this ?: throw IllegalArgumentException("Can't destructure null MatchResult")).groupValues.getOrNull(10) ?: ""
operator fun MatchResult?.component12(): String = (this ?: throw IllegalArgumentException("Can't destructure null MatchResult")).groupValues.getOrNull(11) ?: ""
operator fun MatchResult?.component13(): String = (this ?: throw IllegalArgumentException("Can't destructure null MatchResult")).groupValues.getOrNull(12) ?: ""
operator fun MatchResult?.component14(): String = (this ?: throw IllegalArgumentException("Can't destructure null MatchResult")).groupValues.getOrNull(13) ?: ""
operator fun MatchResult?.component15(): String = (this ?: throw IllegalArgumentException("Can't destructure null MatchResult")).groupValues.getOrNull(14) ?: ""
operator fun MatchResult?.component16(): String = (this ?: throw IllegalArgumentException("Can't destructure null MatchResult")).groupValues.getOrNull(15) ?: ""
operator fun MatchResult?.component17(): String = (this ?: throw IllegalArgumentException("Can't destructure null MatchResult")).groupValues.getOrNull(16) ?: ""
operator fun MatchResult?.component18(): String = (this ?: throw IllegalArgumentException("Can't destructure null MatchResult")).groupValues.getOrNull(17) ?: ""
operator fun MatchResult?.component19(): String = (this ?: throw IllegalArgumentException("Can't destructure null MatchResult")).groupValues.getOrNull(18) ?: ""
operator fun MatchResult?.component20(): String = (this ?: throw IllegalArgumentException("Can't destructure null MatchResult")).groupValues.getOrNull(19) ?: ""
